apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: spe-project
  labels:
    app: image-caption-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-caption-backend

  template:
    metadata:
      labels:
        app: image-caption-backend

    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: shared-model-cache-volume
          persistentVolumeClaim:
            claimName: shared-model-cache-pvc

      initContainers:
        - name: init-caption-model-download
          image: python:3.13-slim
          volumeMounts:
            - name: shared-model-cache-volume
              mountPath: /model-cache
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Init starting..."

              apt-get update && \
              apt-get install -y --no-install-recommends build-essential cmake pkg-config && \
              rm -rf /var/lib/apt/lists/*

              pip install --no-cache-dir transformers torch huggingface_hub sentencepiece pillow

              python <<EOF
import os
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer

MODEL = "nlpconnect/vit-gpt2-image-captioning"
CACHE = "/model-cache/.cache/huggingface"

os.makedirs(CACHE, exist_ok=True)
VisionEncoderDecoderModel.from_pretrained(MODEL, cache_dir=CACHE)
ViTImageProcessor.from_pretrained(MODEL, cache_dir=CACHE)
AutoTokenizer.from_pretrained(MODEL, cache_dir=CACHE)

print("Model downloaded")
EOF

              echo "Init done"

      containers:
        - name: backend
          image: shrutimrao/caption:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-model-cache-volume
              mountPath: /model-cache
