apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: spe-project
  labels:
    app: image-caption-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-caption-backend

  template:
    metadata:
      labels:
        app: image-caption-backend

    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: shared-model-cache-volume
          persistentVolumeClaim:
            claimName: shared-model-cache-pvc

      initContainers:
        - name: init-caption-model-download
          image: python:3.13-slim
          env:
            - name: HF_HOME
              value: /model-cache/.cache/huggingface
            - name: TRANSFORMERS_CACHE
              value: /model-cache/.cache/huggingface
          volumeMounts:
            - name: shared-model-cache-volume
              mountPath: /model-cache
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking for caption model marker..."
              MARKER_FILE="/model-cache/caption_model_downloaded.marker"

              if [ ! -f "$MARKER_FILE" ]; then
                echo "Downloading model..."

                apt-get update && \
                apt-get install -y --no-install-recommends build-essential cmake pkg-config && \
                rm -rf /var/lib/apt/lists/*

                pip install --no-cache-dir --root-user-action=ignore transformers torch huggingface_hub sentencepiece pillow

                python - <<EOF
import sys, os
from transformers import VisionEncoderDecoderModel, ViTImageProcessor, AutoTokenizer

MODEL = "nlpconnect/vit-gpt2-image-captioning"
CACHE = "/model-cache/.cache/huggingface"

try:
    os.makedirs(CACHE, exist_ok=True)
    VisionEncoderDecoderModel.from_pretrained(MODEL, cache_dir=CACHE)
    ViTImageProcessor.from_pretrained(MODEL, cache_dir=CACHE)
    AutoTokenizer.from_pretrained(MODEL, cache_dir=CACHE)
    sys.exit(0)
except Exception as e:
    print(e)
    sys.exit(1)
EOF

                if [ $? -eq 0 ]; then
                  touch "$MARKER_FILE"
                else
                  exit 1
                fi
              else
                echo "Model already exists"
              fi

      containers:
        - name: backend
          image: shrutimrao/caption:build-22
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HF_HOME
              value: /model-cache/.cache/huggingface
            - name: TRANSFORMERS_CACHE
              value: /model-cache/.cache/huggingface
          volumeMounts:
            - name: shared-model-cache-volume
              mountPath: /model-cache
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
